version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cve_data
        #volumes:
      #- mysql_data:/var/lib/mysql

  webui:
    build: .
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=cve_data
    depends_on:
      - mysql

        #volumes:
        #mysql_data:
